[package]
name = "pylon_desktop"
version = "0.11.0"
description = " Cross-platform, secure file transfer desktop application"
authors = ["Nikhil Prabhu <nikhilprabhu98@gmail.com>"]
license = "GPL-3.0"
repository = "https://github.com/nikhil-prabhu/pylon-desktop"
edition = "2021"
rust-version = "1.63.0"

[dependencies]
tauri = { version = "1.2", features = ["clipboard-write-text", "dialog-open", "dialog-save"] }
tauri-plugin-window-state = "0.1.0"
libpylon = "0.11.2"
tokio = { version = "1.26.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
tauri-build = { version = "1.2", features = [] }
chrono = "0.4.23"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libpylon = "0.11.2"

[features]
# by default Tauri runs in production mode
# when `tauri dev` runs it is executed with `cargo run --no-default-features` if `devPath` is an URL
default = ["custom-protocol"]
# this feature is used used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]
