[workspace]
members = ["src-tauri"]

[workspace.package]
authors = ["Nikhil Prabhu <nikhilprabhu98@gmail.com>"]
rust-version = "1.64.0"

[profile.release]
panic = "abort"
lto = true
incremental = true
strip = true
opt-level = "s"
